### ISSUE TITLE
FeatureCollection: name, totalFeatures, crs

### ISSUE THREAD

**Issue by Roland1975** [bamcis-io/GeoJSON#18]
Hi all,

I'm working with GeoJson files whose featureCollection has the following properties:
crs
name
totalFeatures

I don't know if those fields are standard. Nevertheless, "crs" seems important as it declares the format the geoJson was generated with. Example: EPSG:31370, EPSG:4326, etc

`featurecollection.crs = { type: 'name', properties: { name: 'urn:ogc:def:crs:EPSG::4326' } }; //EPSG:4326 `

name: file name
totalFeatures: features length

Do you intend to add those properties to featureCollection any time soon?

**Comment by hakenmt** [comment]
Per the RFC `A FeatureCollection object has a member with the name "features".  The value of "features" is a JSON array. Each element of the array is a Feature object as defined above.` It also specifies that the CRS shall be WGS 84, but has this note:

'the use of alternative coordinate reference systems was specified in [GJ2008], but it has been removed from this version of the specification because the use of different coordinate reference systems -- especially in the manner specified in [GJ2008] -- has proven to have interoperability issues.  In general, GeoJSON processing software is not expected to have access to coordinate reference system databases or to have network access to coordinate reference system transformation parameters.  However, where all involved parties have a prior arrangement, alternative coordinate reference systems can be used without risk of data being misinterpreted.'

The RFC does allow for foreign members to be added to the GeoJSON types, but since none of them are standard, like `crs`, I haven't included any of them in the types. I'm not sure if the `crs` property is prevalent enough to make it part of the base. But you could extend the `FeatureCollection` type to add that property.

**Comment by Roland1975** [comment]
Thanks for your reply.
Regarding coordinate reference system, I disagree :) 
When I collected GeoJson datasets, many were using a system I wasn't aware of. Only crs indicates precisely what the system was. It'd have been impossible to guest it out without the system mentioned explicitly.

I end up deriving FeatureCollection with my own type. The down side is that the code may refer to the library or the the extended version. Alternatively, I could derive all the types you expose. However it mean deriving GeoJson and implementing my own implementation of equals. This turns out to basically rewriting the library.

```
    public class FeatureCollectionExtended : FeatureCollection
    {
        [JsonConstructor]
        public FeatureCollectionExtended(IEnumerable<Feature> features, IDictionary<string, dynamic> crs = null, string name = null, IEnumerable<double> boundingBox = null) : base(features, boundingBox) 
        {
            this.Crs = crs ?? new Dictionary<string, dynamic>();
            this.Name = name ?? string.Empty;
        }

        [JsonProperty(PropertyName = "crs")]
        public IDictionary<string, dynamic> Crs { get; }

        [JsonProperty(PropertyName = "name")]
        public string Name { get; }

        [JsonProperty(PropertyName = "totalFeatures")]
        public int TotalFeatures { get { return this.Features.Count(); } }
    }
```

thanks anyway for your library, a very useful one :)

**Comment by hakenmt** [comment]
For overriding the `Equals()` method, you can still call the base method and then only add in additional logic for Crs, Name, and TotalFeatures (however implementing an Equals function for an `IDictionary<string, dynamic>` could be difficult, might be easier to statically define the tpe and its members). Given the formal definition in the RFC and the flexibility of additional members, I think extending the class is probably the best way to offer broad functionality. Glad this library has been useful for you.

**Comment by Roland1975** [comment]
How do you call the base method? Equals is declared as abstract; as a result, any derived type must provide its own implementation.

Another aspect I'm struggling with is: how do you extend Feature? Unfortunately, I have datasets that are a bit clumsy in terms of rigorousness: typically feature.id instead of feature.properties.id. How do you handle that case?

One way to handle it is to provide a callback from Feature exposing the feature as Json. this allows to access the row feature and extract any stuff. However it requires big changes in the way the library works.

**Comment by hakenmt** [comment]
You could do something like this:

```csharp
public class FeatureCollectionCrs : FeatureCollection
{
    public string Name { get; }

    public IDictionary<string, dynamic> Crs { get; }

    public FeatureCollectionCrs(string name, IEnumerable<Feature> features, IDictionary<string, dynamic> crs, IEnumerable<double> boundingBox = null) : base(features, boundingBox)
    {
        this.Name = name;
        this.Crs = crs;
    }

    public override bool Equals(object obj)
    {
        if (ReferenceEquals(this, obj))
        {
            return true;
        }

        if (obj == null || this.GetType() != obj.GetType())
        {
            return false;
        }

        FeatureCollectionCrs other = (FeatureCollectionCrs)obj;

        return base.Equals(obj) && this.Name.Equals(other.Name) && this.Crs.Equals(other.Crs);
    }
}
```

There's still a little boiler plate in the beginning of Equals, but you really only need to implement the logic for checking equality of the additional properties. `FeatureCollection` declares `Equals` as `public override bool Equals(object obj)`, so it's not abstract, and you don't actually have to implement it in your extended class unless you need/want to check for equality of the additional properties.
