### ISSUE TITLE
What is the value of IPosition?

### ISSUE THREAD

**Issue by SimonCropp** [bamcis-io/GeoJSON#4]
Seems redundant. and none of the other types have interfaces

**Comment by hakenmt** [comment]
To be honest, as the library stands right now, none. I developed this as part of a much larger project at work and was building in some future proofing to allow others to generate their own position classes and ways to generate them, but I never changed the signatures of the constructors methods to use `IPosition` instead of `Position` and I've since moved on from that. I'll probably just delete it unless there's utility in leaving it and updating all of the constructors/methods?

**Comment by SimonCropp** [comment]
+1 for deleting it

**Comment by hakenmt** [comment]
Will remove in next commit.
